### ISSUE TITLE
Unable to open up any dcr

### ISSUE THREAD

**Issue by ThuGie** [Brian151/OpenShockwave#2]
Hey, it seems to only properly show where it go's wrong on chrome,
But on 709
throw PathTooNewError("Codec " + this.chunkArray["RIFX"][0].codec + " unsupported.");

It keeps throwing this as it says pathtoonew i tried different dcr files from 2001 august even..
And it still says its to old, perhaps state what director version is supported with this.
But yes i do know its no where close to finished but still i like that at least somebody is trying this.

**Comment by tomysshadow** [comment]
DCR is not yet supported. Only DIR and DXR are supported. Try using dirOpener in the tools folder first.

And yes, we just got started on this, so it still leaves a lot to be desired. It currently only reads the first handler in every script, and the pseudocode so far only shows calls to external functions and doesn't support variable names.

By the way, we've been testing with DIR/DXR files from Director 4 - 10. (they're mostly the same format, Director 4 handles images a bit differently)

**Comment by Brian151** [comment]
Yeah, and to add to that, our main focus currently would be on parsing the internal structures of regular DIR files, most especially the ones pertaining to bytecode!

DCRs currently can be extracted with DirOpener and offzip.

Hope that's helpful?

Please do be patient. There's a lot of work left to do.... lol.. I wish I could say we had the official specs lying around here somewhere. We don't... /:

**Comment by ThuGie** [comment]
i am more interested in getting to the code,
Anyway diropener does not work for me, it first asks for some xtras when added saying dll error, adding the dll it fully crashes, i made the .dir with dcr to dir 10, that worked, though it fails to make the images etc work for some reason.

When i put that .dir in the upload i get this

`DataStream.js:745 Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at DataStream.readUint32 (DataStream.js:745)
    at OpenShockwaveMovie.chunk.read (projectorrays.js:168)
    at new OpenShockwaveMovie.chunk (projectorrays.js:195)
    at OpenShockwaveMovie.lookupMmap (projectorrays.js:728)
    at FileReader.<anonymous> (projectorrays.js:764)`

And i know its a work in progress and really a LOT to do.
So i will continue to follow this, and see where it ends :) thanks for all the hard work guys!

**Comment by Brian151** [comment]
right... xtras "a modular plugin system, it's great!" probably one of the single biggest problems with shockwave... they didn't work at all as was hoped, they were truly a disaster. for a starter, delete all the xtras and track down whichever versions diropener requires (if they exist anymore) I think it's director/shockwave 8... pretty sure the dll errors are because of xtra versions. furthermore, player/file versions cause problems.

images are something we haven't gotten much to, you can use header-sniffers to find and extract JPEGs, for now though. Same holds true for Flash SWF.

No problem, and I will not easily let this just fizzle-out like all the other efforts have. I want it DONE.

As for that JS error, I'll leave my collaborator to. TBH, this is a problem with external libraries, debugging... That particular error does look fairly coherent, but I haven't really used DataStream for anything, so it's Greek to me.

**Comment by ThuGie** [comment]
Ah i found a .dir i made with diropener long ago, though the output of the script was pretty much blank,
Well it has table headers but no actually data that was what was empty.

**Comment by Brian151** [comment]
the source code will be blank, yes. but much (or even all) of the compiled script could probably be reversed. problem is no one ever completed this... /:

missing xtras and xtra errors can cause dirs to be blank, or even corrupt. what game was it from?

**Comment by ThuGie** [comment]
A old game called spineworld, i made a server from old packet logs i had.
But did never have everything so main reason why i would want to decompile it,
To get packet information and maybe even later recompile the client files aka being able to edit them

**Comment by Brian151** [comment]
what xtras does this require?

**Comment by ThuGie** [comment]
To tell the truth i wouldnt know i unprotected this in like 2016 early.
I could upload the whole client if that could help. and the .dir of the main .dcr file that i think i used diropener for to get.

**Comment by Brian151** [comment]
i suppose, but maybe do the dcr also... diropener very easily could've screwed-up your file... especially if missing or invalid xtras were encountered

**Comment by ThuGie** [comment]
Here are the files,
I remember having to download different shockwave versions to get diropener to do anything haha.
I had so many different xtras versions etc
https://ufile.io/77wld

still got the setup for the shockwave 7 and 8 and i think 12 if i recall, i was mostly interested in 7 and 8 as if i recall thats what it needed.

also got castCopier100-702-1.dir to get unprotected cct files, it might be .dir but script not visible, but does work. just run it form director if you want it as well let me know.

**Comment by Brian151** [comment]
i'm looking at raw data right now since director won't tell me much, and i've fallen back to a computer that i quit using due to overheat issues

found the xtra list, but it could take me a little while to copy...

**Comment by ThuGie** [comment]
If your system is overheating, you might want to clean out the dust and replace the cooling paste :).
99% of the time thats the problem or the fan is broken ?
If no cooling paste most computer store carry it and you need only a lil bit.
Its not something expensive though some store's act like it is.. so check online before you buy from the store just use your mobile to check the brand if it actually that expensive.

Also if you need i could set up a vm to work from.
Home server is pretty much doing nothing atm..

**Comment by Brian151** [comment]
idk if i copied these right
but:
INetUrl PPC Xtra INETURL.X32
NetFile PPC Xtra NETFILE.X32
NetLingo PPC Xtra Netlingo.x32
SWA Decompression PPC Xtra swadcmpr.x32 http://download.macromedia.com/pub/shockwave11.5/xtras/SWA
SWA Decompression PPC Xtra swadcmpr.x32 DirectSound.x32 http://download.macromedia.com/pub/shockwave11.5/xtras/DirectSound DirectSound.x32
Sound Control Sound Control.x32 http://download.macromedia.com/pub/shockwave11.5/xtras/SoundControl Sound Control Sound Control.x32
CoreAudioMix http://download.macromedia.com/pub/shockwave11.5/xtras/CoreAudioMix CoreAudioMix BitmapFilters BitmapFilters.x32 http://download.macromedia.com/pub/shockwave11.5/xtras/BitmapFilters BitmapFilters BitmapFilters.x32
TextAsset PPC Text Asset.x32 http://download.macromedia.com/pub/shockwave11.5/xtras/TextAsset TextAsset PPC Text Asset.x32 TextXtra PPC TextXtra.x32 http://download.macromedia.com/pub/shockwave11.5/xtras/TextXtra TextXtra PPC TextXtra.x32
Font Xtra PPC Font Xtra.x32 http://download.macromedia.com/pub/shockwave11.5/xtras/FontXtra Font Xtra PPC.A Font Xtra.x32

as for my computer:
fan is fine
dust was cleaned-out many times
idk about the putty/paste... 
i do not have a mobile device and am quite fine with that
and this is not really for discussing my computer, so i'll end that discussion

**Comment by ThuGie** [comment]
Sorry about that, working in a computer store just triggered a response :$
Thanks for the list so if i get the files in that list from version 11.5 diropener should work just fine ?

Also if useful not sure
https://github.com/scummvm/scummvm/tree/master/engines/director/lingo/tests
https://github.com/scummvm-director/continuity

http://fileformats.archiveteam.org/wiki/Lingo_bytecode - if i recall for director 4

**Comment by Brian151** [comment]
yeah, i can be the same
It's easy to trigger me when discussing the "open web" should be called the !openWeb since they are FORCING users and developers to choose one technology/API

interesting...
other efforts
i shall review and maybe borrow from, and perhaps reach-out

https://github.com/Brian151/OpenShockwave/tree/master/docu/imports/Lingo_Bytecode

**Comment by ThuGie** [comment]
Seem not to be able to find coreaudiomix
And when adding the xtras i still need to add the .dll so i add those from 11.5 and it crashes :p.
Should i be using from shockwave 8 ?

Also anything that might help you, if they got some info of course you could try asking them.
For me its not a angry trigger, but a oh maybe i can help, cause the problem you talked about occurs a lot.
But i will drop it from now on.

Back on topic.
i also tried the castCopier100-702-1.dir thats pretty much a tool to extract stuff from a cct.
And the code in it works just not visible, yet it still displays only the table head no info underneat it.
Am i messing something up ?

Tried the 2 .html in the Format folder, are they suppose to do anything for .dir files.
Or am i missing a readme ?

**Comment by Brian151** [comment]
i can't help you there... it wouldn't be the first time an xtra has been hard to track-down and/or install. the last official diropener is shockwave 8, yes...

yeah...

umm... idk... could have not exported right?
can't answer why projectorrays wouldn't be reading it. multiple chnages were made, and i need to have those elaborated to me... *facepalm*

umm... it should be ShockwaveTools.html, and you have to edit either the html or the js file to actually open it... idr off the top of my head. sry. also, THAT one indeed doesn't do a lot right now. sry i'm not more helpful, i'm back from a bit of a hiatus due to some tech issues, the latter of which being why i'm on my old computer. anyways, i'm not entirely set-up right now... you're not missing a readme i don't think, i should prob work on those...

**Comment by ThuGie** [comment]
Really you shouldn't worry about things missing etc,
Its normal you are doing hard work.. and there is really no real document's that explain wth director does with the files.
I don't mind waiting for years, as i been waiting since pff 2014 or something.
And yeah tech issues are always a pain. working on those daily

If i might have any xtras you need just tell me i upload it :), you probably already have them all though still i can check.

**Comment by Brian151** [comment]
Yeah, but I also am not well-documenting my own finds, except the format, itself. Not how to use the tools or the APIs. Pretty bad practice...

I am contemplating the submission of the xtra files... I may at least create personal backups of them..

I'm trying not to do anything too risky with what's being shared. Official xtras are pretty risky, imo. Gotta love license terms... 

I probably do not. And I'd have to move to palemoon (probably not an option on this rig) since firefox is killing NPAPI.

**Comment by ThuGie** [comment]
Ah yeah the license stuff, though the files have pretty much always been public so i doubt there will be many problems with it.
And yeah every browser is dropping it, got firefox(nightly) and firefox(stable) but i am pretty sure i had to use if i recall chrome to be able to run it or the stable firefox.

Oh for files i do upload you got a site you rather have me use ? or is ufile.io fine ?

Also got
dirOpener300-800-1-PC.exe
and
dirOpener300-702-1-PC.exe

**Comment by Brian151** [comment]
not really, long as it doesn't serve me invasive ads or do other shady stuff....

**Comment by ThuGie** [comment]
Oh also got castCopier100-702-1.exe if interested in such tools.

**Comment by Brian151** [comment]
that's fine i guess? but a dxr or dir should be fine

**Comment by ThuGie** [comment]
Ah i just added them all.
https://ufile.io/y60yw not sure if i have more tools around but i will send them if i find them.

**Comment by Brian151** [comment]
well... it's definitely got a script in it... 
i can't really say much else unless attempting to decompile it...

here's the iterals data as viewed in a hex editor (as ascii) Input.....input.dcr.................castCopierMembersToCopyDisplay..................castCopierMembersToCopyDisplay..................castCopierMembersToCopyDisplay......All done!

**Comment by ThuGie** [comment]
I can't even remember where i got those from though diropener i got from the original website when it was still online
But right now im going to be getting ready for bed its 2 am, got to get up at 8 today.
Probably still can't sleep though tooth ache :/. Yay.
Though will be keeping a eye on this, and upload anything i find that might be useful though might be useless :p.

**Comment by Brian151** [comment]
ok

**Comment by tomysshadow** [comment]
If you can play the DCR file in your browser but not open it using dirOpener, try copying the Xtras folder from Shockwave 8.5 Projector into dirOpener's directory. Said Shockwave Projector is included in the tools folder in this repo. May help.

dirOpener uses Shockwave 8.5 . It'll only work with Shockwave 8.5 Xtras. The default Xtras are in this repo in the Shockwave 8.5 Projector.

DCR2DIR seems to create incomplete or corrupted files, which is why I don't recommend it, it's an experiment at this point. However, I figure I should probably correct the script error you encountered. It would appear to me that the mmap section is incomplete and is missing the offset to a script. This isn't a problem I've encountered but I'll try and handle the error.

Also, contrary to what Brian has said, not having the required Xtras will cause issues with dirOpener but shouldn't cause any decompilation errors. The function names are in the Lnam chunk and the variables to push/pop are in the Lscr so even if you don't have all the required Xtras the script should still decompile. With that said, pseudocode at this point will be mostly blank, as I'm still writing the code to do this.

**Comment by Brian151** [comment]
yeah..

ok

eh, not entirely... I've had experiences where diropener does create files that are invalid. that might only be with incompatible versions though. having the wrong xtras i think can cause corrupted files to be exported? idr... i've only had that problem a few times... /:

**Comment by ThuGie** [comment]
Also i noticed there are 2 files called protectorrays.js
tools\lscrtoscript\js
tools\Format

not sure if they have diff purposes otherwise maybe put it in the tools directory and access it thru ../protectorrays.js
Cause there code seems to be different like one has been updated and the other not.

Edit:
And how do i get the console output i set loggingEnabled=true in fix js but chrome is not showing anything in the console :/. wrong console or ?

Edit:
http://modelrail.otenko.com/macromedia-director

**Comment by Brian151** [comment]
Before i got to bed (already 3 hours past when i'd like to be...)

what happened is this:
we have two js projects for parsing director files...
the one in 'format', and projectorrays
at some point, they will merge, or one will be discarded. (maybe both and total re-code effort will occur)
projectorrays from the get go focused on disassembly, but only handled bytecode.
the thing in format is a more general approach: entire format, current focus on DIR
due to relative path stuff, idk if i'll reference the most recent projectorrays.js or not. but basically, projectorrays.js is in format because i was trying to proxy script decompilation through it, by feeding it the parsed Lnam chunk and a related Lscr chunk. I however never got far with this, and then I had to switch computers...TWICE... thus an old version of projectorrays sat in format so long. I'll address this soon....

edit1:
no idea...i use firefox, and soon will move to palemoon cuz chrome is overly restrictive

edit2:
alright...
also, as far as scummvm is concerned, IDK how much we really will use it, in any way... GPL license would impose itself on this whole repo, DO NOT WANT... 
(speaking of licenses...we should license this project pretty dang soon!)

**Comment by ThuGie** [comment]
Also a night person i see, :-D
Ah yeah so they did kinda have a diff purpose.

And i just used firefox it did work this time got a proper output thanks!
Ah yeah license issues is indeed a problem.

`OpenShockwaveMovie/this.LingoScript/this.handler.prototype.bytecode.prototype.translate file:///OpenShockwave-master/tools/lscrtoscript/js/projectorrays.js:393:4
	OpenShockwaveMovie/this.LingoScript/this.handler.prototype.write file:///OpenShockwave-master/tools/lscrtoscript/js/projectorrays.js:836:19
	OpenShockwaveMovie/this.lookupMmap file:///OpenShockwave-master/tools/lscrtoscript/js/projectorrays.js:911:70
	OpenShockwaveMovie/ShockwaveMovieReader.onload</< file:///OpenShockwave-master/tools/lscrtoscript/js/projectorrays.js:938:5`

Is what i got with the latest version, no empty table just white page with this message :).
At least firefox is outputting something now instead just giving a error without being able to show where.
I will say i am using firefox nightly for this.

Edit:
Oh you are printing out a varible names bytecode that does not exist only happens with using logging output.
the table does output something now, not quite readable for me yet but hey progress!

Edit2:
Whoa, tried a bit bigger file, firefox kept complaining that it was slowing down lol.
Used up to about 12gb of ram to do the file. it did work though gave a output and everything!
Just took a bit of time to progress it haha.

` on mouseDown 
    _sound.beep() 
end `

results in

bytecode	opcode	pseudocode
114 89	UNK_72 89	
66 1	NEWARGLIST 1	
103 90	UNK_67 90	
1	RET 	exit


I assume unk_72 89 = _sound
and unk_67 90 = beep
inbetween you get a
PUSHBYTE int
if you use a _sound.beep(int)
and of course how big the argument list is no = NEWARGLIST 1 otherwise 2 or higher
I might be wrong as i dont see anywhere where unk or what the format of unk is.

Edit:
I also tried a alert, but its not yet possible to read the strings it has i only get a push 0 for the msg itself.

**Comment by Brian151** [comment]
idk what i am... /:

Chrome likes to restrict the user from doing anything in the ways of local webpage testing, unless you actually set-up a server... LAME...

I couldn't say much about this error...

edit1:
needs some work still i think

edit2:
12 GB?! what size was the file?

I don't think the bytecodes work quite like that? if it's been prefixed with unk, we have yet to determine what it does. thus far, very few built-ins have been encountered which use their own bytecode instruction. most would use the calle (call external) instruction

edit3:
js alert() ?
tbh, not highly recommended, the actual htmls should have an actual console field, though. having to rely on web console honestly isn't ideal.

**Comment by ThuGie** [comment]
nah the alert was in lue of course. with a text, was hoping the decompiler would show it but it does not :p makes sense as its just the beginning,
Around 2,5mb the .dir file was but dont worry got 32gb to run off from so it be fine.
and nope seems does not matter what function/arg you get its always 72 for start and 67 for close.

although i noticed if i have on mouseDown i get whats inside there,
When i do on mouseUp i dont get the code though the table does show.
It often enough only shows just 1 method/function is that correct ?

**Comment by Brian151** [comment]
yeah

umm 2 and a half MB shouldn't take 12 GB to parse, that's just insane! How are you getting this number?

a lot needs to be done... 
Supposedly it decompiles more than one function now?
Probably is having errors with your file, but IDK

**Comment by tomysshadow** [comment]
"Unk" stands for unknown. It means we don't know what that instruction does yet. It's helpful to see the original Lingo code in that case.

Looking at the Lingo code and the bytecode it produced, UNK_67 seems to be some sort of CALL, similar to CALL_EXTERNAL. UNK_72 must be pushing a value, perhaps UNK_72 is pushing the beep function and UNK_67 is calling the first function in the list. It's odd because NEWARGLIST is typically used to wrap arguments in a list before calling a function, but you didn't seem to pass any arguments to the beep function.

It should not be taking 12 GB of RAM to parse at all. I can only guess that one of the loops, either to go through all the scripts or all the bytes in a script, went on way too long.

I added the ability to see all the handlers in a script last night, as well as more work on the pseudocode, but still can't see the names of handlers/variables (I haven't got to parsing the Lctx chunks yet.)

**Comment by ThuGie** [comment]
Well firefox does have a problem loading the page as well, a ton of empty tables but a lot of them are filled tot the brim mostly unk of course.
To get the results i got just do a on mouseClick add _sound.beep() do note beep does take 1 arugment if wanted to say how many beeps aka beep(5)
Though unk_67 and unk_72 are also happening when i do a alert _player.alert("msg")
if i recall seems more a arguOpen argClose kinda deal

Don't have the original source of the 2,5mb file btw.
For other stuff aka testing i just open director type a function and publish then diropener to go back to .dir though original .dir gives same output it seems.
This way i can just call a method see what the output is and what possibly the bytecode stands for.

The parser doesn't have proper doc to see how i can add stuff myself and see the results.

**Comment by Brian151** [comment]
hmm...

ok...?
Well, without the original source, we cannot determine a whole lot. The unknown OPs, especially

Documentation takes time. Mine doesn't yet do a lot, and projectorrays still focueses pretty exclusively on code. Far as I know, they don't need extensive documentation, except in their code.

**Comment by ThuGie** [comment]
ah the unk_72 and unk_67 are from code i do have source from as its just a simple on mouseclick with a _sound.beep in there :p

**Comment by Brian151** [comment]
for now, hard to say what exactly is going on... we haven't really figured-out what each op does.

**Comment by Brian151** [comment]
I think we should keep issues on-topic.
That said, I think this one can safely be closed.
DCR support is planned, and in fact, I will try to work on DCR soon after I resume work on this.
I have some other things that urgently need to be attended to.

If something else should come-up, please open a new issue or file under an existing issue that is related.
That should be everything
